bot-directories=C:\\Users\\LENOVO\\OneDrive - Institut Teknologi Sumatera\\Documents\\Semester 4\\TubesStima\\Tubes_Tantrump\\src\\alternative-bots,true,C:\\Users\\LENOVO\\OneDrive - Institut Teknologi Sumatera\\Documents\\Semester 4\\TubesStima\\Tubes_Tantrump\\src\\main-bot,true
tps=30
